/**
 * Automatically generated by Zserio C++ extension version 1.0.
 */

#ifndef SKIPDICT_VALUES_CLOUD_STORAGE_H
#define SKIPDICT_VALUES_CLOUD_STORAGE_H

#include <string>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/HashCodeUtil.h>
#include <zserio/PreWriteAction.h>
#include <zserio/Types.h>

namespace skipdict
{
namespace values
{

class CloudStorage
{
public:
    /**
     * The type this enum is based on.
     *
     * This is the C++ mapping of the original zserio type. It can be
     * wider than the original type. E.g. "enum bit:3" would have uint8_t
     * as its base type.
     */
    typedef uint8_t _base_type;

    enum e_CloudStorage
    {
        TWO_GB = UINT8_C(0),
        FOUR_GB = UINT8_C(1),
        SIX_GB = UINT8_C(2),
        EIGHT_GB = UINT8_C(3)
    };

    CloudStorage();
    CloudStorage(e_CloudStorage value);
    explicit CloudStorage(zserio::BitStreamReader& _in);

    operator e_CloudStorage() const;
    uint8_t getValue() const;

    size_t bitSizeOf(size_t _bitPosition = 0) const;
    size_t initializeOffsets(size_t _bitPosition = 0) const;

    bool operator==(const CloudStorage& other) const;
    bool operator==(e_CloudStorage other) const;
    int hashCode() const;

    void read(zserio::BitStreamReader& _in);
    void write(zserio::BitStreamWriter& _out,
            zserio::PreWriteAction _preWriteAction = zserio::ALL_PRE_WRITE_ACTIONS) const;

    const char* toString() const;

    static CloudStorage toEnum(uint8_t rawValue);

private:
    e_CloudStorage m_value;
};

} // namespace values
} // namespace skipdict

#endif // SKIPDICT_VALUES_CLOUD_STORAGE_H
