/**
 * Automatically generated by Zserio C++ extension version 1.0.
 */

#ifndef SKIPDICT_VALUES_ROCK_BAND_H
#define SKIPDICT_VALUES_ROCK_BAND_H

#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/BitFieldUtil.h>
#include <zserio/CppRuntimeException.h>
#include <zserio/StringConvertUtil.h>
#include <zserio/PreWriteAction.h>
#include <string>
#include <zserio/Types.h>

namespace skipdict
{
namespace values
{

class RockBand
{
public:
    RockBand();
    RockBand(zserio::BitStreamReader& _in);

    std::string& getName();
    const std::string& getName() const;
    void setName(const std::string& name);

    uint8_t getMembers() const;
    void setMembers(uint8_t members);

    uint64_t getFans() const;
    void setFans(uint64_t fans);

    size_t bitSizeOf(size_t _bitPosition = 0) const;
    size_t initializeOffsets(size_t _bitPosition);

    bool operator==(const RockBand& other) const;
    int hashCode() const;

    void read(zserio::BitStreamReader& _in);
    void write(zserio::BitStreamWriter& _out,
            zserio::PreWriteAction _preWriteAction = zserio::ALL_PRE_WRITE_ACTIONS);

private:
    std::string m_name;
    uint8_t m_members;
    uint64_t m_fans;
};

} // namespace values
} // namespace skipdict

#endif // SKIPDICT_VALUES_ROCK_BAND_H
